### ISSUE TITLE
Add placeholder sound effects

### ISSUE THREAD

**Issue by josh26220** [LateClubStudios/NextGenSynopticProject-Outnumbered#14]
Make our game look more atmospheric using stock sound effects. We could replace them with our own sound effects once we all get into the development stage. Some examples could include footsteps, or the train passing by, or stuff like light wind and other atmospheric folly that we can find.

Here's a list of some possible sound effects:

- [ ] Trains / wheel noises
- [ ] Rumble sound effects
- [ ] Footsteps
- [ ] Combat noises (sheens of the knife, possible grunting etc.)

**Comment by paradox-glitch** [comment]
### Issue Closed 

Final sounds have been added, the temp sounds have been replaced.
