### ISSUE TITLE
Replace Temp Cover System

### ISSUE THREAD

**Issue by josh26220** [LateClubStudios/NextGenSynopticProject-Outnumbered#15]
There is a part in the game where a drone peaks through the window and detects if the player is there, so we need to make a cover system so the player doesn't get spotted by the drone.

We have started with the basics of teleporting the player from one X coordinate to another (smoothing the transition will be an issue later), but so far the animations and the code are jumbled and messed up.

**Comment by paradox-glitch** [comment]
Fixed - now just needs smoothing.

**Comment by paradox-glitch** [comment]
### Issue closed

The system still currently warps the player. but now the player has to be much closer for this to work this is still quite native but it looks OK and works flawlessly.

**Comment by paradox-glitch** [comment]
This could be improved by using lerps to smooth it out.
