### ISSUE TITLE
Bug List - Avail Release

### ISSUE THREAD

**Issue by josh26220** [LateClubStudios/NextGenSynopticProject-Outnumbered#22]
### BUG's IN AVAIL RELEASE ###

- [x] **_Player is able to "wall jump"_**
_Caused By Script that resets jump on collision._
- [x] **_UI missing in maintenance room_**
_Caused By GameObject being turned off in editor_
- [x] **_Settings menu on maintenance room ui doesn't work_**
_Caused By Prefab deleted so script got unpaired from menu dropdowns_
- [x] **_Rotation script needs major tweaking_** 
_Issue - Causes Lag and can be a bit "stiff"
Lag caused by debug logs_
- [x] **_Able to access Start button in settings menu_**
_disable start button UI ellemt when others are active_
- [x] **_Fix death animation_**
- [x] **_Game over scene - post processing FX missing_**
- [x] **_Game over scene - overlapping text on smaller resolutions_**
- [x] **_scene 04 "death scene" didn't build_**
- [x] **_Sound Missing in maintence room_**
- [x] **_Game crashes when using Windows 10 or 4k Resolution_**
- [x] **_Can not see train coming._**
_Train needs to be slowed down, also need to change how far the player can see "outside" the room._
- [x] **Light rays are missing**
- [x] **Hard shadows are missing/broken**
- [ ] **_Player is able to traverse gap without jumping_**
_Problem Caused By:-
PlayerController.cs@67
 if (transform.position.x > 2.5f)
 {
  transform.position = new Vector3 (2.5f, transform.position.y, transform.position.z);
  }
  else if (transform.position.x < -2f)
   {
      transform.position = new Vector3(-2f, transform.position.y, transform.position.z);
}_
- [ ] **Player Controller - "Feels Super Weired"**
- [ ] **Player Controller - Rotation Script keeps spinning if mouse leaves screen**
_It will be fine, once new animations are in place, possible move around some key binds._
- [ ] **Player Controller - Player glitch out map when sprint**
- [ ] **Player glitch though roof when on box**
- [ ] **DragObject script still doesn't work**
- [ ] **Put timers on every function so player doesn't spam inputs**
- [ ] **Tweak the cover system**
- [ ] **World geometry tweak - player can glitch through wall**
_Playered collider become jamed between other coliders. Change players to capsual and change how the colider on rubble functions_ 
- [ ] **If the user quits and starts again, player doesn't move**
- [ ] **Player can double jump**
- [ ] **Restart button on start menu doesn't work**
- [ ] **Box can go through the floor and break the player controller**
- [ ] **Level Has no end - "game pointless"**

_Tick the boxes if the bug has been removed._

**Comment by paradox-glitch** [comment]
Rotation Scripted Fixed - Too many debug logs :)

**Comment by paradox-glitch** [comment]
Start Button access over other ui's fixed - Changed MainMenu Script to disable the panel the start button was on. Also change MenuMenu_Start and linked to the panel off function so the button would not enlarge when hovered over and a UI was open.

**Comment by paradox-glitch** [comment]
Death Animation - Revised PlayerDeath Script to turn off rag-doll when game starts and to turn animator off and rag-doll on when player dies. Added new label that when collides with player causes death.

**Comment by paradox-glitch** [comment]
Gameover scene bugs - Post FX fixed reattached old FX stack, Text overlap fixed changed anchor position to just above and below center.

**Comment by paradox-glitch** [comment]
scene 04 build error - looks like it built but got re-labeled scene02

**Comment by paradox-glitch** [comment]
Sound Missing - Issue Invalid, It works. Probs because ui was off.

**Comment by paradox-glitch** [comment]
Windows 10 or 4K - Marked Invalid, should work, seems to work in next release, just a build error.

**Comment by josh26220** [comment]
Can Not See Train Bug - Slowed the train animation down.

**Comment by paradox-glitch** [comment]
Changed Lighting Box - You can now see train coming.

**Comment by paradox-glitch** [comment]
Lighting Resolved - Now using asset stores "AURA"

**Comment by paradox-glitch** [comment]
### CLOSED - NEW PROJECT FOR LIGHTING SEE NEW BUG LIST.
