### ISSUE TITLE
Bug List - Lighting Update

### ISSUE THREAD

**Issue by paradox-glitch** [LateClubStudios/NextGenSynopticProject-Outnumbered#29]
### Issues that have already been fixed
- [x] **_Player is able to traverse gap without jumping_**
_Problem Caused By:-
PlayerController.cs@67
 if (transform.position.x > 2.5f)
 {
  transform.position = new Vector3 (2.5f, transform.position.y, transform.position.z);
  }
  else if (transform.position.x < -2f)
   {
      transform.position = new Vector3(-2f, transform.position.y, transform.position.z);
}_
- [x] **All build settings are gone**
- [x] **All player settings are gone**
- [x] **Player keeps getting faster over time** 
- [x] **Player can not jump when standing still**
_Problem Caused By:-
PlayerController.cs@143        
else
        {
            GetComponent<Rigidbody>().velocity = Vector3.zero;
            GetComponent<Rigidbody>().angularVelocity = Vector3.zero;
            playerAnimator.SetBool("isWalk", false);
        }_
- [x] **DragObject script still doesn't work**
- [x] **If the user quits and starts again, player doesn't move**
- [x] **Player Controller - Rotation Script keeps spinning if mouse leaves screen**
- [x] **Player can double jump**
- [x] **Hard to see on second floor**
- [x] **Player Controller - Player glitch out map when sprint**
_This needs emphasis. Is the player able to run through any walls or is this referring to running out of the world because there isn't a wall where the train is?_
- [x] **Jumping mechanic does not work properly**
- [x] **Player sinks through the floor when getting up at the beginning of the game**
- [x] **Climbing mechanic needs major tweaking - player is able to float and move fast when holding space bar**
- [x] **Player glitch though roof when on box**
- [x] **If player moves and spams the crouch button, the player moves really fast**
- [x] **Moving off the vaulting box causes the player to move really fast**
- [x] **Put timers on every function so player doesn't spam inputs**
- [x] **Tweak the cover system**
- [x] **Box can go through the floor and break the player controller**
- [x] **Make the function for the drone so the player is killed as soon as he is detected**

### Issues that currently need fixing
- [ ] **RagDoll Issue**
_see issue_ #28 
- [ ] **If player dies and exits to menu, then starts the game again, the player still dies**
_We can either a) disable the ability to pause when the player dies or b) change the variable to make the player alive to true so when the player reenters the level the player will be back to normal._
- [ ] **Add the greyblocking for the other worlds into the other scenes**
- [ ] **Make the function for the door so the player leaves the maintenance room**
- [ ] **Fade transitions between scenes need readding**

### Issues that have little priority or will be assigned to other members
- [ ] **Tunnel section player falls through**
_Floor too thin model with boxes instead of planes, use 0.1m_
- [ ] **Restart button on start menu doesn't work**
- [ ] **Level Has no end - "game pointless"**
- [ ] **Player Controller - "Feels Super Weird"**
_It will be fine, once new animations are in place, possible move around some key binds._
- [ ] **World geometry tweak - player can glitch through wall**
_Player collider become jammed between other colliders. Change players to capsule and change how the collider on rubble functions_ 
- [ ] **Make the AI able to run towards and attack the player**
- [ ] **Make the attack function so that it kills enemies**
- [ ] **Implement health system for the player**
- [ ] **Attach melee weapons to player's hands**
- [ ] **Make a miniature inventory system for the weapons that the player will be holding**
- [ ] **Make the function for the 20 second delay before the player has to hide**

_Tick the boxes if the bug has been removed, and move it to the issues that have been resolved._

**Comment by josh26220** [comment]
> All build settings are gone
> All player settings are gone

Some inputs needed rebinding and some objects needed to be placed to be called via script. The build settings are back to normal as well.

**Comment by paradox-glitch** [comment]
> Player is able to traverse gap without jumping
> Problem Caused By:-
> PlayerController.cs@67
> if (transform.position.x > 2.5f)
> {
> transform.position = new Vector3 (2.5f, transform.position.y, transform.position.z);
> }
> else if (transform.position.x < -2f)
> {
> transform.position = new Vector3(-2f, transform.position.y, transform.position.z);

**Fixed - Reworked the movement system to a physics based one instead of a transform based one. This code is no longer needed as X-Axis colliders work again. There for the player does not [Levitate](https://youtu.be/z0a9k1gSMsw?t=82)**

**Comment by paradox-glitch** [comment]
> Player keeps getting faster over time

**Fixed - Clamping velocity**

**Comment by josh26220** [comment]
> Player can not jump while standing still

He does jump - the jumping mechanic is completely broken.

**Comment by paradox-glitch** [comment]
> DragObject script still doesn't work

**Reworked entire script. Removed perentring and used ther big math insted.**

**Comment by josh26220** [comment]
>Player Controller - Rotation Script keeps spinning if mouse leaves screen

Added a few lines of code to fix this. See `PlayerController` in the `Update()` function.

**Comment by paradox-glitch** [comment]
> Hard to see on second floor

**Replaced Lighting**

**Comment by paradox-glitch** [comment]
> Player Controller - Player glitch out map when sprint

**Fixed when we added the physics controller. **

**Comment by josh26220** [comment]
> Player sinks through floor at the beginning of the game

The "Bake into Pose" checkbox needed to be ticked.

**Comment by paradox-glitch** [comment]
### Issue Closed

Outdated bug list
