### ISSUE TITLE
Connors Jump Function

### ISSUE THREAD

**Issue by paradox-glitch** [LateClubStudios/NextGenSynopticProject-Outnumbered#30]
The jump function, adds a force to the player, this works when the game is running between 85 - 100 FPS, any higher or lower and the player can not make the jump.

**Comment by paradox-glitch** [comment]
- issue is actually because we slowed him down.

**Comment by josh26220** [comment]
I've been experimenting with the movement speeds.

- The player can make the jump at a sprint speed of 15960 (12000 walk speed for realism)
- The player can *barely* make the jump at a sprint speed of 15295 (11500 walk speed)

**Comment by josh26220** [comment]
** FIXED **

I changed the multiplier from ` Time.deltaTime ` to a float so that the player can make it across the gap with ease. I am uncertain if the lower frame rate issue still persists but the jump now works for PCs that run at a smoother framerate.
