### ISSUE TITLE
Some assets outside are not being effected by the lighting. 

### ISSUE THREAD

**Issue by paradox-glitch** [LateClubStudios/NextGenSynopticProject-Outnumbered#48]

**Comment by paradox-glitch** [comment]
![image](https://user-images.githubusercontent.com/35745554/58990976-1d448f80-87df-11e9-9166-dca4f2dd7792.png)

**Comment by DinkyLegs** [comment]
### Issue Closed
Hadn't changed the Opacity from Fade to Opaque
