### ISSUE TITLE
Gameplay enhancements

### ISSUE THREAD

**Issue by josh26220** [LateClubStudios/NextGenSynopticProject-Outnumbered#50]
Upon building the game, there are some noticeable issues that we could probably iron out:

- [x] The "climb down" function is completely useless, and we need to find a way of optimising it in the game. It also completely halts the tutorial.
- [x] The player can take advantage of the turret by walking past it by going towards the screen. - see issue #42 
- [x] Getting killed by the box that prevents you to advance past the turret unless you cover feels unrealistic (snaps into place).
- [x] We can't see the door to leave the maintenance room due to the lighting.
- [x] We also need to add a projector on the door telling the player to press the E button to leave.
- [x] We need to add a projector telling the player they can sprint.

**Comment by paradox-glitch** [comment]
> We can't see the door to leave the maintenance room due to the lighting.

I recommend we put one of those green fire lights and signs above the door.

**Comment by paradox-glitch** [comment]
> We need to add a projector telling the player they can sprint.

> We also need to add a projector on the door telling the player to press the E button to leave.

both these projectors have been added. however the E to leave need changing into attack. 


> We can't see the door to leave the maintenance room due to the lighting.

The door is now partially open, and lights up some of the room. however i still recommend the addition of the fire light.

**Comment by paradox-glitch** [comment]
### Issue Closed
All issues have been fixed.
