### ISSUE TITLE
An option to switch between first person and "third" person?

### ISSUE THREAD

**Issue by josh26220** [LateClubStudios/NextGenSynopticProject-Outnumbered#54]
The implementation of first person is cool, but I don't want to make the stuff we did on the third person controls completely useless, so I say that we make a setting, either in the option menu or readily available in the main menu, where the user can switch between first person mode and third person mode.

The scripts to do this should be simple - we just need to use booleans and reference them in other scripts and use IF statements to check if one is on and one is off, and inside we can turn the script components off depending on what we need to put on.

**Comment by paradox-glitch** [comment]
### Feature Added
_Kinda dont work but its added._
