### ISSUE TITLE
Replace Temp Vaulting System

### ISSUE THREAD

**Issue by paradox-glitch** [LateClubStudios/NextGenSynopticProject-Outnumbered#8]
code works but animator is not working. Players rig resets when you try to move the global position.

**Comment by paradox-glitch** [comment]
Suggestion - Put the current controller inside an empty and then animate that.

**Comment by josh26220** [comment]
### UPDATE

Code currently makes the player warp on top of the box. Need to find a way to make the player smoothly transition on top of the box until we get a vaulting animation. See newest issue.

**Comment by paradox-glitch** [comment]
### Issue Closed
The player now has an animator that vaults. The players nav box is paused while the rig animates on top of the box. once on the box the nav box is unpaused and sent to the players hip position.
